FROM php:7.2-fpm

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y --fix-missing apt-utils gnupg
RUN apt-get install -y wget
RUN apt-get install -y git

RUN apt-get install -y libzip-dev zip
RUN docker-php-ext-configure zip --with-libzip
RUN docker-php-ext-install zip

RUN docker-php-ext-install pdo pdo_mysql

RUN echo "root:password" | chpasswd
RUN useradd -u 1000 --create-home shantanu
USER shantanu
